-- =====================================================================
-- Afirmative Pill · Script único para el SQL Editor de Supabase
-- (GENERADO con `npm run db:bundle` — no editar a mano)
-- Contiene, en orden: migraciones 001-004 y seeds 001-003.
-- =====================================================================

-- >>>>>>>>>>>>>>>>>>>> migrations/001_catalog.sql <<<<<<<<<<<<<<<<<<<<

-- =====================================================================
-- Afirmative Pill · Migración 001 · Catálogo (datos de referencia)
-- ---------------------------------------------------------------------
-- * medications_dataset : copia 1:1 del dataset suministrado (50 filas).
-- * categories / laboratories / medications : catálogo normalizado.
--   La normalización permite relaciones anidadas reales en GraphQL
--   (Medication.category, Medication.laboratory) resueltas con DataLoader.
-- =====================================================================

-- En Supabase las extensiones viven en el schema "extensions".
-- Se crean ahí también en local para que el SQL sea idéntico en ambos.
create schema if not exists extensions;
create extension if not exists pg_trgm  with schema extensions;
create extension if not exists pgcrypto with schema extensions;
create extension if not exists unaccent with schema extensions;

-- ---------------------------------------------------------------------
-- Staging: dataset tal cual fue entregado (se puede importar por CSV)
-- ---------------------------------------------------------------------
create table if not exists medications_dataset (
  id                    integer primary key,
  sku                   text    not null unique,
  name                  text    not null,
  active_ingredient     text    not null,
  category              text    not null,
  dosage                text    not null,
  presentation          text    not null,
  price                 numeric(12, 2) not null,
  stock                 integer not null,
  requires_prescription boolean not null,
  manufacturer          text    not null,
  description           text    not null
);

-- ---------------------------------------------------------------------
-- Catálogo normalizado
-- ---------------------------------------------------------------------
create table if not exists categories (
  id   integer generated by default as identity primary key,
  name text not null unique,
  slug text not null unique
);

create table if not exists laboratories (
  id   integer generated by default as identity primary key,
  name text not null unique
);

create table if not exists medications (
  id                    integer primary key,
  sku                   text    not null unique check (sku ~ '^MED-[0-9]{3}$'),
  name                  text    not null,
  active_ingredient     text    not null,
  category_id           integer not null references categories (id),
  laboratory_id         integer not null references laboratories (id),
  dosage                text    not null,
  presentation          text    not null,
  price                 numeric(12, 2) not null check (price >= 0),
  requires_prescription boolean not null default false,
  description           text    not null,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);

create index if not exists idx_medications_category   on medications (category_id);
create index if not exists idx_medications_laboratory on medications (laboratory_id);

-- >>>>>>>>>>>>>>>>>>>> migrations/002_write_model.sql <<<<<<<<<<<<<<<<<<<<

-- =====================================================================
-- Afirmative Pill · Migración 002 · WRITE MODEL (lado de comandos)
-- ---------------------------------------------------------------------
-- Tablas transaccionales que solo modifican los Command Handlers.
-- Las invariantes críticas se protegen también a nivel de BD
-- (CHECK stock >= 0, un único carrito abierto por usuario, etc.).
-- domain_events funciona como OUTBOX: cada comando registra sus eventos
-- en la MISMA transacción; el proyector los consume de forma asíncrona.
-- =====================================================================

do $$ begin
  create type user_role as enum ('PATIENT', 'PHARMACIST');
exception when duplicate_object then null; end $$;

do $$ begin
  create type order_status as enum ('PENDING_APPROVAL', 'APPROVED', 'DISPATCHED', 'CANCELLED');
exception when duplicate_object then null; end $$;

do $$ begin
  create type prescription_status as enum ('PENDING_REVIEW', 'APPROVED', 'REJECTED');
exception when duplicate_object then null; end $$;

do $$ begin
  create type cart_status as enum ('OPEN', 'CHECKED_OUT');
exception when duplicate_object then null; end $$;

-- ---------------------------------------------------------------------
-- Usuarios (pacientes y químicos farmacéuticos)
-- ---------------------------------------------------------------------
create table if not exists users (
  id              uuid primary key default gen_random_uuid(),
  email           text not null unique check (email = lower(email)),
  full_name       text not null,
  document_number text not null,
  password_hash   text not null,
  role            user_role not null default 'PATIENT',
  created_at      timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- Inventario: fuente de verdad del stock (invariante: nunca negativo)
-- ---------------------------------------------------------------------
create table if not exists inventory (
  medication_id integer primary key references medications (id) on delete cascade,
  stock         integer not null check (stock >= 0),
  version       integer not null default 0,
  updated_at    timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- Carrito (agregado transaccional en el servidor)
-- ---------------------------------------------------------------------
create table if not exists carts (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references users (id) on delete cascade,
  status     cart_status not null default 'OPEN',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists uq_carts_one_open_per_user
  on carts (user_id) where status = 'OPEN';

create table if not exists cart_items (
  cart_id       uuid    not null references carts (id) on delete cascade,
  medication_id integer not null references medications (id),
  quantity      integer not null check (quantity > 0),
  added_at      timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  primary key (cart_id, medication_id)
);

-- ---------------------------------------------------------------------
-- Órdenes
-- ---------------------------------------------------------------------
create sequence if not exists order_code_seq start 1001;

create table if not exists orders (
  id                    uuid primary key default gen_random_uuid(),
  code                  text not null unique
                        default ('AP-' || lpad(nextval('order_code_seq')::text, 6, '0')),
  user_id               uuid not null references users (id),
  cart_id               uuid references carts (id),
  status                order_status not null default 'PENDING_APPROVAL',
  total                 numeric(12, 2) not null check (total >= 0),
  requires_prescription boolean not null,
  shipping_address      text not null,
  idempotency_key       text,
  version               integer not null default 1,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);

create unique index if not exists uq_orders_idempotency
  on orders (user_id, idempotency_key) where idempotency_key is not null;
create index if not exists idx_orders_user   on orders (user_id);
create index if not exists idx_orders_status on orders (status);

create table if not exists order_items (
  id            bigint generated always as identity primary key,
  order_id      uuid    not null references orders (id) on delete cascade,
  medication_id integer not null references medications (id),
  quantity      integer not null check (quantity > 0),
  unit_price    numeric(12, 2) not null check (unit_price >= 0),
  subtotal      numeric(12, 2) not null check (subtotal >= 0),
  unique (order_id, medication_id)
);

create index if not exists idx_order_items_order on order_items (order_id);

-- ---------------------------------------------------------------------
-- Fórmulas médicas (soporte obligatorio para ítems con prescripción)
-- ---------------------------------------------------------------------
create table if not exists prescriptions (
  id               uuid primary key default gen_random_uuid(),
  order_id         uuid not null unique references orders (id) on delete cascade,
  doctor_name      text not null,
  doctor_license   text not null,
  patient_document text not null,
  issued_at        date not null,
  document_url     text,
  notes            text,
  status           prescription_status not null default 'PENDING_REVIEW',
  reviewed_by      uuid references users (id),
  reviewed_at      timestamptz,
  review_notes     text,
  created_at       timestamptz not null default now()
);

create index if not exists idx_prescriptions_status on prescriptions (status);

-- ---------------------------------------------------------------------
-- Outbox de eventos de dominio
-- ---------------------------------------------------------------------
create table if not exists domain_events (
  id             bigint generated always as identity primary key,
  aggregate_type text not null,
  aggregate_id   text not null,
  event_type     text not null,
  payload        jsonb not null,
  occurred_at    timestamptz not null default now(),
  processed_at   timestamptz,
  attempts       integer not null default 0,
  last_error     text
);

create index if not exists idx_domain_events_pending
  on domain_events (id) where processed_at is null;
create index if not exists idx_domain_events_aggregate
  on domain_events (aggregate_type, aggregate_id);

-- >>>>>>>>>>>>>>>>>>>> migrations/003_read_model.sql <<<<<<<<<<<<<<<<<<<<

-- =====================================================================
-- Afirmative Pill · Migración 003 · READ MODEL (lado de consultas)
-- ---------------------------------------------------------------------
-- Proyecciones desnormalizadas y optimizadas para lectura. Solo las
-- escribe el Projector (a partir del outbox domain_events); las Queries
-- GraphQL leen EXCLUSIVAMENTE de estas tablas.
-- =====================================================================

-- ---------------------------------------------------------------------
-- Proyección del catálogo: búsqueda facetada + disponibilidad
-- ---------------------------------------------------------------------
create table if not exists medication_catalog (
  medication_id         integer primary key references medications (id) on delete cascade,
  sku                   text    not null,
  name                  text    not null,
  active_ingredient     text    not null,
  dosage                text    not null,
  presentation          text    not null,
  price                 numeric(12, 2) not null,
  requires_prescription boolean not null,
  description           text    not null,
  category_id           integer not null,
  category_name         text    not null,
  laboratory_id         integer not null,
  laboratory_name       text    not null,
  stock_available       integer not null,
  availability          text    not null
                        check (availability in ('IN_STOCK', 'LOW_STOCK', 'OUT_OF_STOCK')),
  -- Documento de búsqueda precalculado: minúsculas y sin tildes
  -- (nombre comercial + principio activo + categoría + laboratorio + sku)
  search_text           text    not null,
  synced_at             timestamptz not null default now()
);

-- Búsqueda parcial (ILIKE '%texto%') indexada con trigramas
create index if not exists idx_catalog_search_trgm
  on medication_catalog using gin (search_text extensions.gin_trgm_ops);
create index if not exists idx_catalog_ingredient_trgm
  on medication_catalog using gin (lower(active_ingredient) extensions.gin_trgm_ops);
-- Facetas y ordenamientos
create index if not exists idx_catalog_category      on medication_catalog (category_id);
create index if not exists idx_catalog_laboratory    on medication_catalog (laboratory_id);
create index if not exists idx_catalog_prescription  on medication_catalog (requires_prescription);
create index if not exists idx_catalog_availability  on medication_catalog (availability);
create index if not exists idx_catalog_price         on medication_catalog (price, medication_id);
create index if not exists idx_catalog_name          on medication_catalog (name, medication_id);

-- Reconstruye (total o parcialmente) la proyección del catálogo.
-- LOW_STOCK se activa con 25 unidades o menos.
create or replace function refresh_medication_catalog(p_ids integer[] default null)
returns integer
language plpgsql
as $$
declare
  affected integer;
begin
  insert into medication_catalog as mc (
    medication_id, sku, name, active_ingredient, dosage, presentation, price,
    requires_prescription, description, category_id, category_name,
    laboratory_id, laboratory_name, stock_available, availability, search_text, synced_at
  )
  select
    m.id, m.sku, m.name, m.active_ingredient, m.dosage, m.presentation, m.price,
    m.requires_prescription, m.description, c.id, c.name,
    l.id, l.name, i.stock,
    case when i.stock = 0 then 'OUT_OF_STOCK'
         when i.stock <= 25 then 'LOW_STOCK'
         else 'IN_STOCK' end,
    lower(extensions.unaccent(concat_ws(' ', m.name, m.active_ingredient, c.name, l.name, m.sku))),
    now()
  from medications m
  join categories   c on c.id = m.category_id
  join laboratories l on l.id = m.laboratory_id
  join inventory    i on i.medication_id = m.id
  where p_ids is null or m.id = any (p_ids)
  on conflict (medication_id) do update set
    sku                   = excluded.sku,
    name                  = excluded.name,
    active_ingredient     = excluded.active_ingredient,
    dosage                = excluded.dosage,
    presentation          = excluded.presentation,
    price                 = excluded.price,
    requires_prescription = excluded.requires_prescription,
    description           = excluded.description,
    category_id           = excluded.category_id,
    category_name         = excluded.category_name,
    laboratory_id         = excluded.laboratory_id,
    laboratory_name       = excluded.laboratory_name,
    stock_available       = excluded.stock_available,
    availability          = excluded.availability,
    search_text           = excluded.search_text,
    synced_at             = excluded.synced_at;

  get diagnostics affected = row_count;
  return affected;
end;
$$;

-- ---------------------------------------------------------------------
-- Proyección de órdenes: resumen listo para pintar en la UI
-- ---------------------------------------------------------------------
create table if not exists order_projections (
  order_id              uuid primary key,
  code                  text not null,
  user_id               uuid not null,
  customer_name         text not null,
  status                order_status not null,
  total                 numeric(12, 2) not null,
  item_count            integer not null,
  items                 jsonb not null,           -- [{medicationId, sku, name, quantity, unitPrice, subtotal, requiresPrescription}]
  requires_prescription boolean not null,
  prescription          jsonb,                    -- {status, doctorName, doctorLicense, issuedAt, reviewNotes, reviewedAt}
  shipping_address      text not null,
  status_history        jsonb not null default '[]'::jsonb,  -- [{status, at, note, actor}]
  placed_at             timestamptz not null,
  updated_at            timestamptz not null,
  projection_version    integer not null default 1,
  last_event_id         bigint  not null,
  synced_at             timestamptz not null default now()
);

create index if not exists idx_order_proj_user   on order_projections (user_id, placed_at desc);
create index if not exists idx_order_proj_status on order_projections (status, placed_at desc);

-- >>>>>>>>>>>>>>>>>>>> migrations/004_security.sql <<<<<<<<<<<<<<<<<<<<

-- =====================================================================
-- Afirmative Pill · Migración 004 · Seguridad (Zero-REST)
-- ---------------------------------------------------------------------
-- Supabase expone automáticamente una API REST (PostgREST) sobre las
-- tablas del schema public. Para cumplir el mandato Zero-REST se activa
-- Row Level Security SIN políticas: los roles anon/authenticated de la
-- Data API quedan sin acceso y el ÚNICO camino a los datos es el
-- backend GraphQL (que se conecta con el rol dueño de las tablas).
-- =====================================================================

alter table medications_dataset enable row level security;
alter table categories          enable row level security;
alter table laboratories        enable row level security;
alter table medications         enable row level security;
alter table users               enable row level security;
alter table inventory           enable row level security;
alter table carts               enable row level security;
alter table cart_items          enable row level security;
alter table orders              enable row level security;
alter table order_items         enable row level security;
alter table prescriptions       enable row level security;
alter table domain_events       enable row level security;
alter table medication_catalog  enable row level security;
alter table order_projections   enable row level security;

-- >>>>>>>>>>>>>>>>>>>> seed/001_medications_dataset.sql <<<<<<<<<<<<<<<<<<<<

-- =====================================================================
-- Afirmative Pill · Seed 001 · Dataset de 50 medicamentos (Supabase)
-- ---------------------------------------------------------------------
-- Transcripción fiel del dataset suministrado. Se corrigieron 3 erratas
-- tipográficas evidentes del archivo original:
--   * MED-017 active_ingredient: "Hdoclorotiazida" -> "Hidroclorotiazida"
--   * MED-034 active_ingredient: "Aprazolam"       -> "Alprazolam"
--   * MED-050 presentation:      "Frsco x 500 ml"  -> "Frasco x 500 ml"
-- =====================================================================

insert into medications_dataset
  (id, sku, name, active_ingredient, category, dosage, presentation, price, stock, requires_prescription, manufacturer, description)
values
  (1,  'MED-001', 'Acetaminofén Forte',              'Paracetamol',                     'Analgésicos',         '500 mg',                   'Caja x 20 tabletas',                9500,  120, false, 'Laboratorios MK',      'Alivio del dolor de cabeza y cuadros febriles leves a moderados.'),
  (2,  'MED-002', 'Ibuprofeno Max',                  'Ibuprofeno',                      'Antiinflamatorios',   '800 mg',                   'Caja x 30 tabletas',                18200, 85,  false, 'Genfar',               'Antiinflamatorio no esteroideo para dolores articulares y musculares.'),
  (3,  'MED-003', 'Amoxicilina Clavulanato',         'Amoxicilina + Ácido Clavulánico', 'Antibióticos',        '875/125 mg',               'Caja x 14 tabletas',                46000, 40,  true,  'Sandoz',               'Antibiótico de amplio espectro para infecciones respiratorias bacterianas.'),
  (4,  'MED-004', 'Loratadina Antiallerg',           'Loratadina',                      'Antihistamínicos',    '10 mg',                    'Caja x 10 tabletas',                8900,  150, false, 'Tecnoquímicas',        'Tratamiento sintomático de rinitis alérgica y urticaria crónica.'),
  (5,  'MED-005', 'Omeprazol GastroProtect',         'Omeprazol',                       'Gastrointestinal',    '20 mg',                    'Caja x 28 cápsulas',                14500, 110, false, 'Lafrancol',            'Inhibidor de la bomba de protones para reflujo gástrico y úlceras.'),
  (6,  'MED-006', 'Losartán Potásico',               'Losartán',                        'Cardiovascular',      '50 mg',                    'Caja x 30 tabletas',                16800, 95,  true,  'Genfar',               'Antihipertensivo antagonista de los receptores de angiotensina II.'),
  (7,  'MED-007', 'Metformina Clorhidrato',          'Metformina',                      'Endocrinología',      '850 mg',                   'Caja x 30 tabletas',                21000, 75,  true,  'Merck',                'Hipoglucemiante oral para control de glucemia en diabetes tipo 2.'),
  (8,  'MED-008', 'Atorvastatina Lipid',             'Atorvastatina',                   'Cardiovascular',      '20 mg',                    'Caja x 30 tabletas',                32500, 60,  true,  'Pfizer',               'Regulador lipídico para reducir colesterol LDL y triglicéridos.'),
  (9,  'MED-009', 'Cetirizina Dihidrocloruro',       'Cetirizina',                      'Antihistamínicos',    '10 mg',                    'Caja x 10 tabletas',                11200, 130, false, 'Bayer',                'Antihistamínico de segunda generación para cuadros alérgicos agudos.'),
  (10, 'MED-010', 'Azitromicina Unidosis',           'Azitromicina',                    'Antibióticos',        '500 mg',                   'Caja x 3 tabletas',                 28900, 50,  true,  'Genfar',               'Macrólido indicado en infecciones del tracto respiratorio y piel.'),
  (11, 'MED-011', 'Esomeprazol Dual',                'Esomeprazol',                     'Gastrointestinal',    '40 mg',                    'Caja x 14 cápsulas',                39000, 45,  false, 'AstraZeneca',          'Tratamiento avanzado de esofagitis erosiva por reflujo gastroesofágico.'),
  (12, 'MED-012', 'Clonazepam Sedafast',             'Clonazepam',                      'Psiquiatría / Neuro', '2 mg',                     'Caja x 30 tabletas',                27400, 25,  true,  'Roche',                'Benzodiacepina indicada en trastornos de pánico y crisis convulsivas.'),
  (13, 'MED-013', 'Diclofenaco Sódico',              'Diclofenaco',                     'Antiinflamatorios',   '50 mg',                    'Caja x 20 tabletas',                12300, 105, false, 'Laboratorios MK',      'Analgésico antiinflamatorio para dolor agudo postraumático.'),
  (14, 'MED-014', 'Sertralina Anxiofree',            'Sertralina',                      'Psiquiatría / Neuro', '50 mg',                    'Caja x 30 tabletas',                48500, 35,  true,  'Pfizer',               'Antidepresivo inhibidor selectivo de la recaptación de serotonina.'),
  (15, 'MED-015', 'Salbutamol Aerosol HFA',          'Salbutamol',                      'Respiratorio',        '100 mcg/dosis',            'Inhalador 200 dosis',               24900, 80,  false, 'GlaxoSmithKline',      'Broncodilatador de acción rápida para crisis asmáticas y broncoespasmo.'),
  (16, 'MED-016', 'Ciprofloxacino Bacterial',        'Ciprofloxacino',                  'Antibióticos',        '500 mg',                   'Caja x 10 tabletas',                26000, 42,  true,  'Bayer',                'Fluoroquinolona de amplio espectro para infecciones urinarias complejas.'),
  (17, 'MED-017', 'Hidroclorotiazida Diur',          'Hidroclorotiazida',               'Cardiovascular',      '25 mg',                    'Caja x 30 tabletas',                9800,  90,  true,  'Genfar',               'Diurético tiazídico coadyuvante en el manejo de la hipertensión arterial.'),
  (18, 'MED-018', 'Naproxeno Sódico',                'Naproxeno',                       'Antiinflamatorios',   '550 mg',                   'Caja x 12 tabletas',                15400, 115, false, 'Bayer',                'Alivio potente del dolor inflamatorio osteomuscular y dental.'),
  (19, 'MED-019', 'Dexametasona Depo',               'Dexametasona',                    'Corticosteroides',    '4 mg/2 ml',                'Ampolla inyectable x 1',            8500,  65,  true,  'Laboratorios MK',      'Corticoide sistémico potente para crisis alérgicas e inflamatorias severas.'),
  (20, 'MED-020', 'Levotiroxina Sódica',             'Levotiroxina',                    'Endocrinología',      '100 mcg',                  'Caja x 50 tabletas',                31000, 70,  true,  'Abbott',               'Hormona tiroidea sintética de reemplazo en hipotiroidismo primario.'),
  (21, 'MED-021', 'Trimebutina Antispas',            'Trimebutina',                     'Gastrointestinal',    '200 mg',                   'Caja x 30 tabletas',                34500, 55,  false, 'Sanofi',               'Regulador de la motilidad digestiva para síndrome de colon irritable.'),
  (22, 'MED-022', 'Fluconazol Dermic',               'Fluconazol',                      'Antimicóticos',       '150 mg',                   'Caja x 2 cápsulas',                 19800, 85,  false, 'Pfizer',               'Antifúngico triazólico para candidiasis mucocutánea y sistémica.'),
  (23, 'MED-023', 'Enalapril Maleato',               'Enalapril',                       'Cardiovascular',      '20 mg',                    'Caja x 30 tabletas',                11500, 100, true,  'Genfar',               'Inhibidor de la ECA para tratamiento de falla cardíaca e hipertensión.'),
  (24, 'MED-024', 'Clorfeniramina Maleato',          'Clorfeniramina',                  'Antihistamínicos',    '4 mg',                     'Caja x 20 tabletas',                6500,  140, false, 'Laboratorios MK',      'Antihistamínico clásico para rinitis estacional y prurito alérgico.'),
  (25, 'MED-025', 'Butilbromuro de Hioscina',        'Hioscina',                        'Gastrointestinal',    '10 mg',                    'Caja x 10 grageas',                 13800, 90,  false, 'Boehringer Ingelheim', 'Antiespasmódico visceral para cólicos abdominales y renales.'),
  (26, 'MED-026', 'Tramadol Gotas',                  'Tramadol Clorhidrato',            'Analgésicos',         '100 mg/ml',                'Frasco gotero 10 ml',               32000, 30,  true,  'Grunenthal',           'Analgésico opioide atípico para dolor moderado a severo refractario.'),
  (27, 'MED-027', 'Pregabalina Neuropain',           'Pregabalina',                     'Psiquiatría / Neuro', '75 mg',                    'Caja x 28 cápsulas',                56000, 45,  true,  'Pfizer',               'Modulador neuronal para neuropatía diabética y fibromialgia.'),
  (28, 'MED-028', 'Lansoprazol Gastric',             'Lansoprazol',                     'Gastrointestinal',    '30 mg',                    'Caja x 14 cápsulas',                22500, 65,  false, 'Tecnoquímicas',        'Inhibidor gástrico para cicatrización de úlcera duodenal activa.'),
  (29, 'MED-029', 'Metoprolol Tartrato',             'Metoprolol',                      'Cardiovascular',      '50 mg',                    'Caja x 30 tabletas',                14200, 80,  true,  'AstraZeneca',          'Betabloqueador selectivo para arritmias y cardiopatía isquémica.'),
  (30, 'MED-030', 'Cefalexina Monohidrato',          'Cefalexina',                      'Antibióticos',        '500 mg',                   'Caja x 24 cápsulas',                33500, 50,  true,  'Laboratorios MK',      'Cefalosporina de primera generación para infecciones de piel y tejidos.'),
  (31, 'MED-031', 'Aciclovir Dermacare',             'Aciclovir',                       'Antivirales',         '5%',                       'Tubo crema x 15 g',                 16700, 75,  false, 'Genfar',               'Antiviral tópico específico para herpes simple labial y genital inicial.'),
  (32, 'MED-032', 'Insulina Glargina Pen',           'Insulina Glargina',               'Endocrinología',      '100 UI/ml',                'Pluma precargada 3 ml',             89000, 20,  true,  'Sanofi',               'Análogo de insulina de acción ultraprolongada para diabetes mellitus.'),
  (33, 'MED-033', 'Meloxicam Flex',                  'Meloxicam',                       'Antiinflamatorios',   '15 mg',                    'Caja x 10 tabletas',                17900, 90,  false, 'Laboratorios MK',      'Antiinflamatorio preferencial COX-2 para osteoartritis y artritis.'),
  (34, 'MED-034', 'Alprazolam Calmpill',             'Alprazolam',                      'Psiquiatría / Neuro', '0.5 mg',                   'Caja x 30 tabletas',                29000, 25,  true,  'Pfizer',               'Tranquilizante menor para crisis de angustia y ansiedad generalizada.'),
  (35, 'MED-035', 'Budesonida PulmoInhaler',         'Budesonida',                      'Respiratorio',        '200 mcg/dosis',            'Inhalador 200 dosis',               49500, 40,  true,  'AstraZeneca',          'Corticoide inhalado para control de mantenimiento en asma persistente.'),
  (36, 'MED-036', 'Carvedilol HeartCare',            'Carvedilol',                      'Cardiovascular',      '25 mg',                    'Caja x 30 tabletas',                24000, 60,  true,  'Roche',                'Betabloqueador no selectivo vasodilatador en insuficiencia cardíaca.'),
  (37, 'MED-037', 'Furosemida Renal',                'Furosemida',                      'Cardiovascular',      '40 mg',                    'Caja x 30 tabletas',                8700,  110, true,  'Genfar',               'Diurético de asa de alta potencia para edemas periféricos y pulmonares.'),
  (38, 'MED-038', 'Ketoconazol Medipill',            'Ketoconazol',                     'Antimicóticos',       '2%',                       'Frasco champú 120 ml',              28500, 50,  false, 'Janssen',              'Tratamiento antimicótico para dermatitis seborreica y pitiriasis.'),
  (39, 'MED-039', 'Montelukast Broncho',             'Montelukast',                     'Respiratorio',        '10 mg',                    'Caja x 30 tabletas',                44000, 55,  false, 'Merck',                'Antagonista de receptores de leucotrienos para prevención asmática.'),
  (40, 'MED-040', 'Prednisona Immunocort',           'Prednisona',                      'Corticosteroides',    '20 mg',                    'Caja x 30 tabletas',                22000, 70,  true,  'Laboratorios MK',      'Inmunosupresor y antiinflamatorio esteroideo sistémico de rescate.'),
  (41, 'MED-041', 'Domperidona Gastrofluid',         'Domperidona',                     'Gastrointestinal',    '10 mg',                    'Caja x 20 tabletas',                15800, 80,  false, 'Sanofi',               'Procinético y antiemético para náuseas y vaciamiento gástrico lento.'),
  (42, 'MED-042', 'Claritromicina Protect',          'Claritromicina',                  'Antibióticos',        '500 mg',                   'Caja x 10 tabletas',                41000, 35,  true,  'Abbott',               'Antibiótico macrólido coadyuvante en erradicación de H. pylori.'),
  (43, 'MED-043', 'Simvastatina Stat',               'Simvastatina',                    'Cardiovascular',      '20 mg',                    'Caja x 30 tabletas',                13500, 90,  true,  'Genfar',               'Estatina para control primario de dislipidemias e hipercolesterolemia.'),
  (44, 'MED-044', 'Ácido Acetilsalicílico Cardio',   'Ácido Acetilsalicílico',          'Cardiovascular',      '100 mg',                   'Caja x 30 tabletas',                11000, 160, false, 'Bayer',                'Antiagregante plaquetario profiláctico para eventos cardiovasculares.'),
  (45, 'MED-045', 'Miconazol Crema Vag',             'Miconazol',                       'Antimicóticos',       '2%',                       'Tubo crema x 40 g + aplicadores',   21500, 45,  false, 'Genfar',               'Antimicótico ginecológico local para vulvovaginitis fúngica.'),
  (46, 'MED-046', 'Glibenclamida Diabet',            'Glibenclamida',                   'Endocrinología',      '5 mg',                     'Caja x 30 tabletas',                9200,  85,  true,  'Laboratorios MK',      'Sulfonilurea estimulante de secreción de insulina pancreática.'),
  (47, 'MED-047', 'Betametasona Valerato',           'Betametasona',                    'Dermatológico',       '0.10%',                    'Tubo crema x 30 g',                 14900, 70,  true,  'Genfar',               'Corticosteroide dermatológico tópico para dermatosis inflamatorias.'),
  (48, 'MED-048', 'Sucralfato Gastromucosa',         'Sucralfato',                      'Gastrointestinal',    '1 g',                      'Caja x 20 sobres granulado',        37500, 40,  false, 'Laboratorios MK',      'Citoprotector gástrico de barrera mecánica sobre úlceras pépticas.'),
  (49, 'MED-049', 'Levofloxacino Bactrimax',         'Levofloxacino',                   'Antibióticos',        '750 mg',                   'Caja x 7 tabletas',                 58000, 30,  true,  'Sanofi',               'Quinolona respiratoria de alta dosis para neumonía bacteriana adquirida.'),
  (50, 'MED-050', 'Electrolitos Orales Pediátricos', 'Sales de Rehidratación Oral',     'Pediatría / Sueros',  'Electrolitos balanceados', 'Frasco x 500 ml solución oral',     8500,  120, false, 'Abbott',               'Rehidratación oral para prevención de deshidratación por diarrea o vómito.')
on conflict (id) do nothing;

-- >>>>>>>>>>>>>>>>>>>> seed/002_normalize_catalog.sql <<<<<<<<<<<<<<<<<<<<

-- =====================================================================
-- Afirmative Pill · Seed 002 · Normalización del dataset
-- ---------------------------------------------------------------------
-- medications_dataset  ->  categories + laboratories + medications
--                      ->  inventory (write model: stock real)
--                      ->  medication_catalog (read model proyectado)
-- Es idempotente: se puede ejecutar varias veces sin duplicar datos.
-- =====================================================================

insert into categories (name, slug)
select distinct
  d.category,
  trim(both '-' from regexp_replace(lower(extensions.unaccent(d.category)), '[^a-z0-9]+', '-', 'g'))
from medications_dataset d
on conflict (name) do nothing;

insert into laboratories (name)
select distinct d.manufacturer
from medications_dataset d
on conflict (name) do nothing;

insert into medications (
  id, sku, name, active_ingredient, category_id, laboratory_id,
  dosage, presentation, price, requires_prescription, description
)
select
  d.id, d.sku, d.name, d.active_ingredient, c.id, l.id,
  d.dosage, d.presentation, d.price, d.requires_prescription, d.description
from medications_dataset d
join categories   c on c.name = d.category
join laboratories l on l.name = d.manufacturer
on conflict (id) do nothing;

insert into inventory (medication_id, stock)
select d.id, d.stock
from medications_dataset d
on conflict (medication_id) do nothing;

-- Construye la proyección de lectura completa del catálogo
select refresh_medication_catalog();

-- >>>>>>>>>>>>>>>>>>>> seed/003_demo_users.sql <<<<<<<<<<<<<<<<<<<<

-- =====================================================================
-- Afirmative Pill · Seed 003 · Usuarios de demostración
-- ---------------------------------------------------------------------
-- Contraseñas con bcrypt (pgcrypto). El backend las verifica con crypt().
--   Paciente:      paciente@afirmativepill.co  /  Paciente123*
--   Farmacéutico:  farmacia@afirmativepill.co  /  Farmacia123*
-- =====================================================================

insert into users (email, full_name, document_number, password_hash, role)
values
  ('paciente@afirmativepill.co', 'Paciente Demo', '1000000001',
   extensions.crypt('Paciente123*', extensions.gen_salt('bf', 10)), 'PATIENT'),
  ('farmacia@afirmativepill.co', 'Químico Farmacéutico Demo', '1000000002',
   extensions.crypt('Farmacia123*', extensions.gen_salt('bf', 10)), 'PHARMACIST')
on conflict (email) do nothing;
