-- =====================================================================
-- Afirmative Pill · Migración 001 · Catálogo (datos de referencia)
-- ---------------------------------------------------------------------
-- * medications_dataset : copia 1:1 del dataset suministrado (50 filas).
-- * categories / laboratories / medications : catálogo normalizado.
--   La normalización permite relaciones anidadas reales en GraphQL
--   (Medication.category, Medication.laboratory) resueltas con DataLoader.
-- =====================================================================

-- En Supabase las extensiones viven en el schema "extensions".
-- Se crean ahí también en local para que el SQL sea idéntico en ambos.
create schema if not exists extensions;
create extension if not exists pg_trgm  with schema extensions;
create extension if not exists pgcrypto with schema extensions;
create extension if not exists unaccent with schema extensions;

-- ---------------------------------------------------------------------
-- Staging: dataset tal cual fue entregado (se puede importar por CSV)
-- ---------------------------------------------------------------------
create table if not exists medications_dataset (
  id                    integer primary key,
  sku                   text    not null unique,
  name                  text    not null,
  active_ingredient     text    not null,
  category              text    not null,
  dosage                text    not null,
  presentation          text    not null,
  price                 numeric(12, 2) not null,
  stock                 integer not null,
  requires_prescription boolean not null,
  manufacturer          text    not null,
  description           text    not null
);

-- ---------------------------------------------------------------------
-- Catálogo normalizado
-- ---------------------------------------------------------------------
create table if not exists categories (
  id   integer generated by default as identity primary key,
  name text not null unique,
  slug text not null unique
);

create table if not exists laboratories (
  id   integer generated by default as identity primary key,
  name text not null unique
);

create table if not exists medications (
  id                    integer primary key,
  sku                   text    not null unique check (sku ~ '^MED-[0-9]{3}$'),
  name                  text    not null,
  active_ingredient     text    not null,
  category_id           integer not null references categories (id),
  laboratory_id         integer not null references laboratories (id),
  dosage                text    not null,
  presentation          text    not null,
  price                 numeric(12, 2) not null check (price >= 0),
  requires_prescription boolean not null default false,
  description           text    not null,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);

create index if not exists idx_medications_category   on medications (category_id);
create index if not exists idx_medications_laboratory on medications (laboratory_id);
